# Generated by Django 5.0 on 2024-03-18 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PredictionApp', '0003_surveyresults_ct_prediction'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveyresults',
            name='image_path',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
