# Generated by Django 5.0 on 2024-03-18 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PredictionApp', '0004_surveyresults_image_path'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LoginInfo',
        ),
        migrations.RemoveField(
            model_name='surveyresults',
            name='patient_id',
        ),
        migrations.DeleteModel(
            name='PatientInfo',
        ),
        migrations.DeleteModel(
            name='SurveyResults',
        ),
    ]
