# Generated by Django 5.0 on 2024-03-18 11:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('PredictionApp', '0005_delete_logininfo_remove_surveyresults_patient_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PatientInfo',
            fields=[
                ('patient_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='SurveyResults',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('smoking', models.IntegerField()),
                ('yellow_fingers', models.IntegerField()),
                ('anxiety', models.IntegerField()),
                ('peer_pressure', models.IntegerField()),
                ('chronic_disease', models.IntegerField()),
                ('fatigue', models.IntegerField()),
                ('allergy', models.IntegerField()),
                ('wheezing', models.IntegerField()),
                ('alcohol_consuming', models.IntegerField()),
                ('coughing', models.IntegerField()),
                ('shortness_of_breath', models.IntegerField()),
                ('swallowing_difficulty', models.IntegerField()),
                ('chest_pain', models.IntegerField()),
                ('text_prediction', models.BooleanField(default=False)),
                ('text_prediction_percentage', models.FloatField()),
                ('ct_prediction', models.CharField(blank=True, max_length=255, null=True)),
                ('image_path', models.URLField(blank=True, max_length=255, null=True)),
                ('patient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PredictionApp.patientinfo')),
            ],
        ),
    ]
