# Generated by Django 5.0 on 2024-03-18 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PredictionApp', '0006_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LoginInfo',
        ),
    ]
